const pieces = {
  whitePawn0: {
    hasMoved: false,
    avatar: 'white-pawn',
    id: 'whitePawn0',
    name: 'White Pawn',
    color: 'white',
    type: 'pawn',
  },
  whitePawn1: {
    hasMoved: false,
    avatar: 'white-pawn',
    id: 'whitePawn1',
    name: 'White Pawn',
    color: 'white',
    type: 'pawn',
  },
  whitePawn2: {
    hasMoved: false,
    avatar: 'white-pawn',
    id: 'whitePawn2',
    name: 'White Pawn',
    color: 'white',
    type: 'pawn',
  },
  whitePawn3: {
    hasMoved: false,
    avatar: 'white-pawn',
    id: 'whitePawn3',
    name: 'White Pawn',
    color: 'white',
    type: 'pawn',
  },
  whitePawn4: {
    hasMoved: false,
    avatar: 'white-pawn',
    id: 'whitePawn4',
    name: 'White Pawn',
    color: 'white',
    type: 'pawn',
  },
  whitePawn5: {
    hasMoved: false,
    avatar: 'white-pawn',
    id: 'whitePawn5',
    name: 'White Pawn',
    color: 'white',
    type: 'pawn',
  },
  whitePawn6: {
    hasMoved: false,
    avatar: 'white-pawn',
    id: 'whitePawn6',
    name: 'White Pawn',
    color: 'white',
    type: 'pawn',
  },
  whitePawn7: {
    hasMoved: false,
    avatar: 'white-pawn',
    id: 'whitePawn7',
    name: 'White Pawn',
    color: 'white',
    type: 'pawn',
  },
  whiteRook0: {
    hasMoved: false,
    alive: true,
    avatar: 'white-rook',
    id: 'whiteRook0',
    name: 'White Rook',
    color: 'white',
    type: 'rook',
  },
  whiteRook1: {
    hasMoved: false,
    alive: true,
    avatar: 'white-rook',
    id: 'whiteRook1',
    name: 'White Rook',
    color: 'white',
    type: 'rook',
  },
  whiteKnight0: {
    hasMoved: false,
    avatar: 'white-knight',
    id: 'whiteKnight0',
    alive: true,
    name: 'White Knight',
    color: 'white',
    type: 'knight',
  },
  whiteKnight1: {
    hasMoved: false,
    avatar: 'white-knight',
    id: 'whiteKnight1',
    alive: true,
    name: 'White Knight',
    color: 'white',
    type: 'knight',
  },
  whiteBishop0: {
    hasMoved: false,
    avatar: 'white-bishop',
    id: 'whiteBishop0',
    alive: true,
    name: 'White Bishop',
    color: 'white',
    type: 'bishop',
  },
  whiteBishop1: {
    hasMoved: false,
    avatar: 'white-bishop',
    id: 'whiteBishop1',
    alive: true,
    name: 'White Bishop',
    color: 'white',
    type: 'bishop',
  },
  whiteKing: {
    hasMoved: false,
    inCheck: false,
    location: [0, 3],
    avatar: 'white-king',
    id: 'whiteKing',
    alive: true,
    name: 'White King',
    color: 'white',
    type: 'king',
  },
  whiteQueen: {
    hasMoved: false,
    avatar: 'white-queen',
    id: 'whiteQueen',
    alive: true,
    name: 'White Queen',
    color: 'white',
    type: 'queen',
  },
  blackPawn0: {
    hasMoved: false,
    avatar: 'black-pawn',
    id: 'blackPawn0',
    name: 'Black Pawn',
    color: 'black',
    type: 'pawn',
  },
  blackPawn1: {
    hasMoved: false,
    avatar: 'black-pawn',
    id: 'blackPawn1',
    name: 'Black Pawn',
    color: 'black',
    type: 'pawn',
  },
  blackPawn2: {
    hasMoved: false,
    avatar: 'black-pawn',
    id: 'blackPawn2',
    name: 'Black Pawn',
    color: 'black',
    type: 'pawn',
  },
  blackPawn3: {
    hasMoved: false,
    avatar: 'black-pawn',
    id: 'blackPawn3',
    name: 'Black Pawn',
    color: 'black',
    type: 'pawn',
  },
  blackPawn4: {
    hasMoved: false,
    avatar: 'black-pawn',
    id: 'blackPawn4',
    name: 'Black Pawn',
    color: 'black',
    type: 'pawn',
  },
  blackPawn5: {
    hasMoved: false,
    avatar: 'black-pawn',
    id: 'blackPawn5',
    name: 'Black Pawn',
    color: 'black',
    type: 'pawn',
  },
  blackPawn6: {
    hasMoved: false,
    avatar: 'black-pawn',
    id: 'blackPawn6',
    name: 'Black Pawn',
    color: 'black',
    type: 'pawn',
  },
  blackPawn7: {
    hasMoved: false,
    avatar: 'black-pawn',
    id: 'blackPawn7',
    name: 'Black Pawn',
    color: 'black',
    type: 'pawn',
  },
  blackRook0: {
    hasMoved: false,
    avatar: 'black-rook',
    id: 'blackRook0',
    alive: true,
    name: 'Black Rook',
    color: 'black',
    type: 'rook',
  },
  blackRook1: {
    hasMoved: false,
    avatar: 'black-rook',
    id: 'blackRook0',
    alive: true,
    name: 'Black Rook',
    color: 'black',
    type: 'rook',
  },

  blackKnight0: {
    hasMoved: false,
    avatar: 'black-knight',
    id: 'blackKnight0',
    alive: true,
    name: 'Black Knight',
    color: 'black',
    type: 'knight',
  },
  blackKnight1: {
    hasMoved: false,
    avatar: 'black-knight',
    id: 'blackKnight1',
    alive: true,
    name: 'Black Knight',
    color: 'black',
    type: 'knight',
  },
  blackBishop0: {
    hasMoved: false,
    avatar: 'black-bishop',
    id: 'blackBishop0',
    alive: true,
    name: 'Black Bishop',
    color: 'black',
    type: 'bishop',
  },
  blackBishop1: {
    hasMoved: false,
    avatar: 'black-bishop',
    id: 'blackBishop1',
    alive: true,
    name: 'Black Bishop',
    color: 'black',
    type: 'bishop',
  },
  blackKing: {
    hasMoved: false,
    inCheck: false,
    location: [7, 4],
    avatar: 'black-king',
    id: 'blackKing',
    alive: true,
    name: 'Black King',
    color: 'black',
    type: 'king',
  },
  blackQueen: {
    hasMoved: false,
    avatar: 'black-queen',
    id: 'blackQueen',
    alive: true,
    name: 'Black Queen',
    color: 'black',
    type: 'queen',
  },
};

export default pieces;
